import Head from 'next/head';
import Backlog from '../src/components/Backlog';

const BacklogPage = () => (
	<div>
		<Head>
			<title>My Backlog</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="apple-touch-icon" sizes="180x180" href="/iphone180.png" />
		</Head>
		<main>
			<Backlog />
		</main>
	</div>
);

export default BacklogPage;
