import Head from 'next/head';
import Login from '../src/components/Login';

const LoginPage = () => (
	<div>
		<Head>
			<title>My Backlog</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="apple-touch-icon" sizes="180x180" href="/iphone180.png" />
		</Head>
		<main>
			<Login />
		</main>
	</div>
);

export default LoginPage;
