import Head from 'next/head';

import Home from '../src/components/Home';

const Homepage = () => (
	<div>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main>
			<Home />
		</main>
	</div>
);

export default Homepage;
