import Head from 'next/head';
import Login from '../src/components/Login';

const LoginPage = () => (
	<div>
		<Head>
			<title>My Backlog - Login</title>
			<meta name="description" content="Generated by create next app" />
		</Head>
		<main>
			<Login />
		</main>
	</div>
);

export default LoginPage;
